services:
  mi350test:
    build:
      context: ../
      dockerfile: docker/Dockerfile.mi350test
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    volumes:
      - ../:/app
      - ../../rocprofiler-sdk-internal:/rocprofiler-sdk-internal
    ports:
      - 8050:8050
    tty: true
    stdin_open: true