name: Sync Staging with Develop
on:
    workflow_dispatch:
    schedule:
      - cron: 0 5 * * sun

jobs:
  promote-dev-to-stg:
    if: github.repository == 'ROCm/rocprofiler-compute'
    runs-on: ubuntu-latest
    name: Promote Develop to Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            ref: amd-staging
            fetch-depth: '0'

      - name: Merge - Fast Forward Only
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout amd-staging
          git checkout -b promote-develop-$(date +%F)
          git merge --ff-only origin/develop
          git push -u origin HEAD
          gh pr create --base amd-staging --title "Promote \`develop\` to \`amd-staging\`" --fill --label "automerge"
